# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [1]:
from numpy import * #Load all the numpy packages



### A Note About "import as"

    import * 
This loads all submodules. Note: this is a waste of memory when incorporated into deployed code. 
We'll use it here by example - it's fine to use for learning purposes and legibility.

As we'll see later, the proper convention is to use:

    import numpy as np
    
And then to specifically call needed methods:

![](http://note.io/1juA60F)

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [2]:
# Creating arrays
a = zeros((3))
b = ones((2,3))
c = random.randint(1,10,(2,3,4))
d = arange(0,11,1)

What are these functions?

    arange?

In [3]:
# Note the way each array is printed:
a,b,c,d


(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[5, 4, 4, 1],
         [2, 1, 2, 3],
         [1, 4, 2, 7]],
 
        [[3, 8, 2, 6],
         [6, 9, 8, 9],
         [4, 9, 3, 9]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [4]:
## Arithmetic in arrays is element wise

In [5]:
 a = array( [20,30,40,50] )
 b = arange( 4 )
 b

array([0, 1, 2, 3])

In [6]:
 c = a-b
 c

array([20, 29, 38, 47])

In [ ]:
 b**2

## Indexing, Slicing and Iterating

In [ ]:
# one-dimensional arrays work like lists:
a = arange(10)**2

In [ ]:
a

In [ ]:
a[2:5]

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [ ]:
b = random.randint(1,100,(4,4))

In [ ]:
b

In [ ]:
# Guess the output
print(b[2,3])
print(b[0,0])


In [ ]:
b[0:3,1],b[:,1]

In [ ]:
b[1:3,:]

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
dates = pd.date_range('20140101',periods=6)
dates

<class 'pandas.tseries.index.DatetimeIndex'>
[2014-01-01, ..., 2014-01-06]
Length: 6, Freq: D, Timezone: None

In [13]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [17]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01  0.731803  2.318341 -0.126191 -0.903675
2014-01-02  0.161877 -0.892566  0.967681 -1.514520
2014-01-03  0.776626  1.797420  0.916972  0.634322
2014-01-04  2.020242 -0.763612  1.239145 -0.919727
2014-01-05  0.772058  0.417369 -0.957359 -0.916665
2014-01-06 -1.670217 -3.249906  2.017370  1.674340

[6 rows x 4 columns]

In [18]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B  C  D    E
0  1 2013-01-02  1  3  foo
1  1 2013-01-02  1  3  foo
2  1 2013-01-02  1  3  foo
3  1 2013-01-02  1  3  foo

[4 rows x 5 columns]

In [19]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [20]:
df.head()

A         B         C         D
2014-01-01  0.731803  2.318341 -0.126191 -0.903675
2014-01-02  0.161877 -0.892566  0.967681 -1.514520
2014-01-03  0.776626  1.797420  0.916972  0.634322
2014-01-04  2.020242 -0.763612  1.239145 -0.919727
2014-01-05  0.772058  0.417369 -0.957359 -0.916665

[5 rows x 4 columns]

In [21]:
df.tail()

A         B         C         D
2014-01-02  0.161877 -0.892566  0.967681 -1.514520
2014-01-03  0.776626  1.797420  0.916972  0.634322
2014-01-04  2.020242 -0.763612  1.239145 -0.919727
2014-01-05  0.772058  0.417369 -0.957359 -0.916665
2014-01-06 -1.670217 -3.249906  2.017370  1.674340

[5 rows x 4 columns]

In [ ]:
df.index

In [22]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.465398 -0.062159  0.676270 -0.324321
std    1.210982  2.034606  1.055549  1.214187
min   -1.670217 -3.249906 -0.957359 -1.514520
25%    0.304359 -0.860328  0.134600 -0.918962
50%    0.751930 -0.173121  0.942326 -0.910170
75%    0.775484  1.452408  1.171279  0.249823
max    2.020242  2.318341  2.017370  1.674340

[8 rows x 4 columns]

In [24]:
df.sort_values(by='B')
df

A         B         C         D
2014-01-01  0.731803  2.318341 -0.126191 -0.903675
2014-01-02  0.161877 -0.892566  0.967681 -1.514520
2014-01-03  0.776626  1.797420  0.916972  0.634322
2014-01-04  2.020242 -0.763612  1.239145 -0.919727
2014-01-05  0.772058  0.417369 -0.957359 -0.916665
2014-01-06 -1.670217 -3.249906  2.017370  1.674340

[6 rows x 4 columns]

### Selection

In [27]:
df[['A','B']]

A         B
2014-01-01  0.731803  2.318341
2014-01-02  0.161877 -0.892566
2014-01-03  0.776626  1.797420
2014-01-04  2.020242 -0.763612
2014-01-05  0.772058  0.417369
2014-01-06 -1.670217 -3.249906

[6 rows x 2 columns]

In [ ]:
df[0:3]

In [30]:
# By label
df.loc[dates[0]]

A    0.731803
B    2.318341
C   -0.126191
D   -0.903675
Name: 2014-01-01 00:00:00, dtype: float64

In [36]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  0.731803  2.318341
2014-01-02  0.161877 -0.892566
2014-01-03  0.776626  1.797420

[3 rows x 2 columns]

In [37]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02 -0.892566
2014-01-03  1.797420
2014-01-04 -0.763612

[3 rows x 1 columns]

In [38]:
# Fast access to scalar
df.at[dates[1],'B']

-0.89256621998616326

In [99]:
# iloc provides integer locations similar to np style
df.iloc[3:]

0         1         2         3
3  0.391398 -1.516230  1.048406  0.701124
4 -0.403329  0.985176 -0.662832  1.364494
5 -1.301493  0.022856  1.355778 -0.507397
6 -0.138657 -0.803180 -1.871863 -2.733682
7  0.831005 -0.704077 -0.443044 -1.652427
8  0.843654 -0.247104 -1.796185  0.407472
9 -0.588443 -0.190753 -1.648457  0.602659

[7 rows x 4 columns]

### Boolean Indexing

In [42]:
df[df.A < 0] # Basically a 'where' operation

A         B        C        D
2014-01-06 -1.670217 -3.249906  2.01737  1.67434

[1 rows x 4 columns]

### Setting

In [48]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [49]:
df_posA

A         B         C         D
2014-01-01  0.731803  2.318341 -0.126191 -0.903675
2014-01-02  0.161877 -0.892566  0.967681 -1.514520
2014-01-03  0.776626  1.797420  0.916972  0.634322
2014-01-04  2.020242 -0.763612  1.239145 -0.919727
2014-01-05  0.772058  0.417369 -0.957359 -0.916665
2014-01-06  1.670217  3.249906 -2.017370 -1.674340

[6 rows x 4 columns]

In [ ]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [ ]:
s1

In [ ]:
df['F'] = s1

In [ ]:
df

### Missing Data

In [ ]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [ ]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [ ]:
df1

In [ ]:
# find where values are null
pd.isnull(df1)

### Operations

In [ ]:
df.describe()

In [ ]:
df.mean(),df.mean(1) # Operation on two different axes

### Applying functions

In [ ]:
df

In [ ]:
df.apply(np.cumsum)

In [ ]:
df.apply(lambda x: x.max() - x.min())

In [ ]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

### Merge

In [ ]:
random.randn(10,4)

In [72]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -0.479463 -0.309077  0.985786 -0.430858
1  1.183417  1.475100  0.010896  0.889048
2 -0.848505  1.126434  0.573976 -0.278058
3  0.391398 -1.516230  1.048406  0.701124
4 -0.403329  0.985176 -0.662832  1.364494
5 -1.301493  0.022856  1.355778 -0.507397
6 -0.138657 -0.803180 -1.871863 -2.733682
7  0.831005 -0.704077 -0.443044 -1.652427
8  0.843654 -0.247104 -1.796185  0.407472
9 -0.588443 -0.190753 -1.648457  0.602659

[10 rows x 4 columns]

In [82]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
0 -0.479463 -0.309077  0.985786 -0.430858
1  1.183417  1.475100  0.010896  0.889048
2 -0.848505  1.126434  0.573976 -0.278058

[3 rows x 4 columns],
           0         1         2         3
3  0.391398 -1.516230  1.048406  0.701124
4 -0.403329  0.985176 -0.662832  1.364494
5 -1.301493  0.022856  1.355778 -0.507397
6 -0.138657 -0.803180 -1.871863 -2.733682

[4 rows x 4 columns],
           0         1         2         3
7  0.831005 -0.704077 -0.443044 -1.652427
8  0.843654 -0.247104 -1.796185  0.407472
9 -0.588443 -0.190753 -1.648457  0.602659

[3 rows x 4 columns]]

In [75]:
pd.concat(pieces)

0         1         2         3
0 -0.479463 -0.309077  0.985786 -0.430858
1  1.183417  1.475100  0.010896  0.889048
2 -0.848505  1.126434  0.573976 -0.278058
3  0.391398 -1.516230  1.048406  0.701124
4 -0.403329  0.985176 -0.662832  1.364494
5 -1.301493  0.022856  1.355778 -0.507397
6 -0.138657 -0.803180 -1.871863 -2.733682
7  0.831005 -0.704077 -0.443044 -1.652427
8  0.843654 -0.247104 -1.796185  0.407472
9 -0.588443 -0.190753 -1.648457  0.602659

[10 rows x 4 columns]

In [91]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -0.479463 -0.309077  0.985786 -0.430858
1  1.183417  1.475100  0.010896  0.889048
2 -0.848505  1.126434  0.573976 -0.278058
3  0.391398 -1.516230  1.048406  0.701124
4 -0.403329  0.985176 -0.662832  1.364494
5 -1.301493  0.022856  1.355778 -0.507397
6 -0.138657 -0.803180 -1.871863 -2.733682
7  0.831005 -0.704077 -0.443044 -1.652427
8  0.843654 -0.247104 -1.796185  0.407472
9 -0.588443 -0.190753 -1.648457  0.602659

[10 rows x 4 columns]

### Grouping


In [ ]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [ ]:
df

In [ ]:
df.groupby(['A','B']).sum()

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [ ]:
a = df.groupby(['A','B']).sum()

In [ ]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

### Time Series


In [53]:
import pandas as pd
import numpy as np

In [54]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [55]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [56]:
ts

2014-01-01 00:00:00     29
2014-01-01 00:00:01     40
2014-01-01 00:00:02    261
2014-01-01 00:00:03    376
2014-01-01 00:00:04     73
2014-01-01 00:00:05    383
2014-01-01 00:00:06    121
2014-01-01 00:00:07     34
2014-01-01 00:00:08    278
2014-01-01 00:00:09    498
2014-01-01 00:00:10    478
2014-01-01 00:00:11     19
2014-01-01 00:00:12    347
2014-01-01 00:00:13    125
2014-01-01 00:00:14    203
...
2014-01-01 00:01:25     70
2014-01-01 00:01:26    152
2014-01-01 00:01:27    464
2014-01-01 00:01:28    104
2014-01-01 00:01:29    270
2014-01-01 00:01:30    109
2014-01-01 00:01:31    103
2014-01-01 00:01:32    296
2014-01-01 00:01:33    499
2014-01-01 00:01:34     11
2014-01-01 00:01:35    144
2014-01-01 00:01:36    490
2014-01-01 00:01:37     61
2014-01-01 00:01:38    141
2014-01-01 00:01:39    364
Freq: S, Length: 100

In [57]:
# Built in resampling
ts.resample('1Min',how='mean') # Resample secondly to 1Minutely

2014-01-01 00:00:00    266.016667
2014-01-01 00:01:00    190.875000
Freq: T, dtype: float64

In [58]:
# Many additional time series features
ts. #use tab

SyntaxError: invalid syntax (<ipython-input-58-5c9240a56f62>, line 2)

### Plotting


In [67]:
ts.plot()

In [68]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [69]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [71]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas